CREATE TABLE SALARIES 
(ID number(*,0) NOT NULL PRIMARY KEY,
EMPLOYEE_ID number(*,0), 
PROYECT_ID number(*,0), 
SALARY number (10,2), 
EMPLOYEE_PK INT CONSTRAINT FK_SALARY_EMPLOYEE REFERENCES EMPLOYEES (id) NOT NULL, 
PROYECT_PK INT CONSTRAINT FK_SALARY_PROYECT REFERENCES PROYECT (id) NOT NULL)


CREATE TABLE PROYECT 
(ID number(*,0)NOT NULL PRIMARY KEY,
CODE VARCHAR2(255),  
MANAGER_ID number(*,0),     
BUTGET number (10,2), 
DATE_OF_BEGINNING DATE,
DATE_OF_ENDING DATE,
MANAGER_PK INT CONSTRAINT FK_MANAGER_PROYECT REFERENCES EMPLOYEES (id) NOT NULL)

create TABLE EMPLOYEES 
(ID number(*,0) NOT NULL PRIMARY KEY,  
MANAGER_ID number(*,0),     
DATE_OF_JOINING DATE, 
FULL_NAME VARCHAR2(255),
MANAGER_PK INT CONSTRAINT FK_MANAGER REFERENCES EMPLOYEES (ID) NOT NULL)



