CREATE TABLE SALARIES 
(ID number(*,0) NOT NULL PRIMARY KEY,
EMPLOYEE_ID number(*,0), 
PROYECT_ID number(*,0), 
SALARY number (10,2), 
EMPLOYEE_PK INT CONSTRAINT FK_SALARY_EMPLOYEE REFERENCES EMPLOYEES (id) NOT NULL, 
PROYECT_PK INT CONSTRAINT FK_SALARY_PROYECT REFERENCES PROYECT (id) NOT NULL)


CREATE TABLE PROYECT 
(ID number(*,0)NOT NULL PRIMARY KEY,
CODE VARCHAR2(255),  
MANAGER_ID number(*,0),     
BUTGET number (10,2), 
DATE_OF_BEGINNING DATE,
DATE_OF_ENDING DATE,
MANAGER_PK INT CONSTRAINT FK_MANAGER_PROYECT REFERENCES EMPLOYEES (id) NOT NULL)

create TABLE EMPLOYEES 
(ID number(*,0) NOT NULL PRIMARY KEY,  
MANAGER_ID number(*,0),     
DATE_OF_JOINING DATE, 
FULL_NAME VARCHAR2(255),
MANAGER_PK INT CONSTRAINT FK_MANAGER REFERENCES EMPLOYEES (ID) NOT NULL)

select * from PROYECT


INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (1.0,'Holmes Manning',NULL,to_date('2/6/18', 'MM/DD/RR'));
--Fila 2
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (2.0,'Drew Rosario',1.0,to_date('8/5/12', 'MM/DD/RR'));
--Fila 3
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (3.0,'Emery Kelley',1.0,to_date('3/5/16', 'MM/DD/RR'));
--Fila 4
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (4.0,'Baker Petersen',1.0,to_date('3/26/11', 'MM/DD/RR'));
--Fila 5
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (5.0,'Keaton Osborne',1.0,to_date('6/4/14', 'MM/DD/RR'));
--Fila 6
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (6.0,'Salvador Shannon',1.0,to_date('11/25/12', 'MM/DD/RR'));
--Fila 7
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (7.0,'Edan Wilkerson',1.0,to_date('11/20/14', 'MM/DD/RR'));
--Fila 8
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (8.0,'Jerome Carlson',1.0,to_date('2/21/18', 'MM/DD/RR'));
--Fila 9
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (9.0,'Castor Cotton',1.0,to_date('10/1/14', 'MM/DD/RR'));
--Fila 10
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (10.0,'Jack Mccarty',8.0,to_date('2/5/15', 'MM/DD/RR'));
--Fila 11
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (11.0,'Michael Figueroa',9.0,to_date('6/21/12', 'MM/DD/RR'));
--Fila 12
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (12.0,'Theodore Lowe',7.0,to_date('1/17/17', 'MM/DD/RR'));
--Fila 13
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (13.0,'Quinn Calderon',11.0,to_date('10/17/13', 'MM/DD/RR'));
--Fila 14
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (14.0,'Vaughan Hickman',7.0,to_date('3/8/18', 'MM/DD/RR'));
--Fila 15
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (15.0,'Aquila Herring',11.0,to_date('7/18/13', 'MM/DD/RR'));
--Fila 16
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (16.0,'Ali Bright',14.0,to_date('12/7/16', 'MM/DD/RR'));
--Fila 17
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (17.0,'Philip Russo',7.0,to_date('2/18/16', 'MM/DD/RR'));
--Fila 18
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (18.0,'Samson Bass',7.0,to_date('4/16/15', 'MM/DD/RR'));
--Fila 19
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (19.0,'Nathan Goff',17.0,to_date('10/6/17', 'MM/DD/RR'));
--Fila 20
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (20.0,'Reese White',10.0,to_date('2/11/16', 'MM/DD/RR'));
--Fila 21
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (21.0,'Cruz Yates',20.0,to_date('3/5/13', 'MM/DD/RR'));
--Fila 22
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (22.0,'Eric Haynes',8.0,to_date('2/8/17', 'MM/DD/RR'));
--Fila 23
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (23.0,'Rafael Hester',7.0,to_date('11/24/13', 'MM/DD/RR'));
--Fila 24
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (24.0,'Kermit Gibson',12.0,to_date('10/25/14', 'MM/DD/RR'));
--Fila 25
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (25.0,'Axel Terrell',8.0,to_date('10/22/13', 'MM/DD/RR'));
--Fila 26
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (26.0,'Dominic Little',19.0,to_date('11/29/10', 'MM/DD/RR'));
--Fila 27
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (27.0,'Ezekiel Rogers',8.0,to_date('8/8/14', 'MM/DD/RR'));
--Fila 28
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (28.0,'Tate Sheppard',14.0,to_date('7/3/14', 'MM/DD/RR'));
--Fila 29
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (29.0,'Erich Shelton',27.0,to_date('11/16/16', 'MM/DD/RR'));
--Fila 30
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (30.0,'Otto Wood',14.0,to_date('2/11/17', 'MM/DD/RR'));
--Fila 31
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (31.0,'Dexter Wilson',7.0,to_date('6/22/13', 'MM/DD/RR'));
--Fila 32
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (32.0,'Ulysses Craft',12.0,to_date('3/9/13', 'MM/DD/RR'));
--Fila 33
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (33.0,'Bernard Salazar',27.0,to_date('11/21/11', 'MM/DD/RR'));
--Fila 34
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (34.0,'Tyler Reyes',17.0,to_date('10/17/12', 'MM/DD/RR'));
--Fila 35
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (35.0,'Plato Carter',35.0,to_date('1/25/14', 'MM/DD/RR'));
--Fila 36
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (36.0,'Amos Terry',11.0,to_date('11/16/14', 'MM/DD/RR'));
--Fila 37
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (37.0,'Hamilton Kent',12.0,to_date('8/2/10', 'MM/DD/RR'));
--Fila 38
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (38.0,'Kenneth Carr',22.0,to_date('12/23/15', 'MM/DD/RR'));
--Fila 39
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (39.0,'Hasad Curry',21.0,to_date('1/19/11', 'MM/DD/RR'));
--Fila 40
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (40.0,'Demetrius Cleveland',30.0,to_date('8/17/16', 'MM/DD/RR'));
--Fila 41
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (41.0,'Bruno Little',8.0,to_date('11/1/16', 'MM/DD/RR'));
--Fila 42
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (42.0,'Orlando Sanchez',28.0,to_date('12/7/12', 'MM/DD/RR'));
--Fila 43
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (43.0,'Leo Riley',6.0,to_date('3/24/13', 'MM/DD/RR'));
--Fila 44
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (44.0,'Aquila Alvarado',35.0,to_date('6/6/14', 'MM/DD/RR'));
--Fila 45
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (45.0,'Adrian Pena',43.0,to_date('1/16/18', 'MM/DD/RR'));
--Fila 46
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (46.0,'Walker Allen',39.0,to_date('12/27/16', 'MM/DD/RR'));
--Fila 47
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (47.0,'Ferdinand Knapp',19.0,to_date('3/15/17', 'MM/DD/RR'));
--Fila 48
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (48.0,'Graham Dotson',24.0,to_date('4/18/17', 'MM/DD/RR'));
--Fila 49
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (49.0,'Kermit Macias',8.0,to_date('8/14/16', 'MM/DD/RR'));
--Fila 50
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (50.0,'Dieter Sweeney',34.0,to_date('11/3/16', 'MM/DD/RR'));
--Fallo de inserción en las filas  51  mediante  100 
--ORA-01400: cannot insert NULL into ("PARCIALUNO"."EMPLOYEES"."MANAGER_PK")
--Fila 51
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (51.0,'Jonas Pope',7.0,to_date('6/23/10', 'MM/DD/RR'));
--Fila 52
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (52.0,'Chadwick Knowles',41.0,to_date('9/27/10', 'MM/DD/RR'));
--Fila 53
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (53.0,'Fulton Lloyd',30.0,to_date('4/9/10', 'MM/DD/RR'));
--Fila 54
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (54.0,'Colin Hale',21.0,to_date('7/19/13', 'MM/DD/RR'));
--Fila 55
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (55.0,'Tobias Ford',8.0,to_date('6/22/14', 'MM/DD/RR'));
--Fila 56
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (56.0,'Leroy Webster',11.0,to_date('11/12/16', 'MM/DD/RR'));
--Fila 57
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (57.0,'Herrod Abbott',13.0,to_date('7/14/10', 'MM/DD/RR'));
--Fila 58
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (58.0,'Scott Walton',40.0,to_date('3/17/10', 'MM/DD/RR'));
--Fila 59
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (59.0,'Jack Harrell',30.0,to_date('4/2/15', 'MM/DD/RR'));
--Fila 60
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (60.0,'Lane Tanner',43.0,to_date('12/9/17', 'MM/DD/RR'));
--Fila 61
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (61.0,'Leo Horton',37.0,to_date('11/1/14', 'MM/DD/RR'));
--Fila 62
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (62.0,'Cairo Hubbard',16.0,to_date('7/28/10', 'MM/DD/RR'));
--Fila 63
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (63.0,'Benedict Stein',29.0,to_date('1/18/13', 'MM/DD/RR'));
--Fila 64
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (64.0,'Armand Davidson',14.0,to_date('9/28/14', 'MM/DD/RR'));
--Fila 65
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (65.0,'Alexander Guthrie',43.0,to_date('1/17/16', 'MM/DD/RR'));
--Fila 66
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (66.0,'Odysseus Hawkins',43.0,to_date('4/10/17', 'MM/DD/RR'));
--Fila 67
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (67.0,'Hamish Fernandez',63.0,to_date('6/20/16', 'MM/DD/RR'));
--Fila 68
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (68.0,'Vincent Morales',18.0,to_date('8/8/11', 'MM/DD/RR'));
--Fila 69
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (69.0,'Benedict Mcfarland',48.0,to_date('6/3/13', 'MM/DD/RR'));
--Fila 70
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (70.0,'Bruce Glenn',39.0,to_date('7/25/11', 'MM/DD/RR'));
--Fila 71
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (71.0,'Kermit Herman',65.0,to_date('2/3/11', 'MM/DD/RR'));
--Fila 72
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (72.0,'Hilel Calhoun',25.0,to_date('2/7/18', 'MM/DD/RR'));
--Fila 73
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (73.0,'Nathan Franklin',50.0,to_date('12/17/14', 'MM/DD/RR'));
--Fila 74
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (74.0,'Axel Ayala',19.0,to_date('5/27/14', 'MM/DD/RR'));
--Fila 75
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (75.0,'Armand Thornton',38.0,to_date('8/7/10', 'MM/DD/RR'));
--Fila 76
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (76.0,'Nigel Poole',17.0,to_date('5/20/10', 'MM/DD/RR'));
--Fila 77
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (77.0,'Chase Sutton',43.0,to_date('12/8/11', 'MM/DD/RR'));
--Fila 78
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (78.0,'Kieran Camacho',20.0,to_date('12/7/15', 'MM/DD/RR'));
--Fila 79
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (79.0,'Lewis Holman',61.0,to_date('2/24/16', 'MM/DD/RR'));
--Fila 80
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (80.0,'Reuben Briggs',7.0,to_date('4/23/15', 'MM/DD/RR'));
--Fila 81
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (81.0,'Amos Peck',69.0,to_date('3/6/12', 'MM/DD/RR'));
--Fila 82
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (82.0,'Sylvester Crane',44.0,to_date('2/7/16', 'MM/DD/RR'));
--Fila 83
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (83.0,'Marshall Mcgowan',77.0,to_date('12/2/10', 'MM/DD/RR'));
--Fila 84
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (84.0,'Harrison Blanchard',59.0,to_date('1/28/12', 'MM/DD/RR'));
--Fila 85
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (85.0,'Chancellor Franco',14.0,to_date('10/4/17', 'MM/DD/RR'));
--Fila 86
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (86.0,'Sean Mcneil',16.0,to_date('8/21/11', 'MM/DD/RR'));
--Fila 87
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (87.0,'Quamar Lee',62.0,to_date('3/31/15', 'MM/DD/RR'));
--Fila 88
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (88.0,'Zane Lamb',68.0,to_date('2/10/15', 'MM/DD/RR'));
--Fila 89
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (89.0,'Slade Gonzalez',8.0,to_date('8/5/15', 'MM/DD/RR'));
--Fila 90
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (90.0,'Nehru Mcintyre',63.0,to_date('5/22/13', 'MM/DD/RR'));
--Fila 91
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (91.0,'Clarke Fisher',70.0,to_date('10/11/16', 'MM/DD/RR'));
--Fila 92
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (92.0,'Honorato Gamble',33.0,to_date('2/4/11', 'MM/DD/RR'));
--Fila 93
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (93.0,'Clarke Banks',66.0,to_date('9/21/17', 'MM/DD/RR'));
--Fila 94
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (94.0,'Jakeem Buck',64.0,to_date('8/15/15', 'MM/DD/RR'));
--Fila 95
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (95.0,'Hakeem Baldwin',34.0,to_date('3/3/17', 'MM/DD/RR'));
--Fila 96
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (96.0,'Wallace Marquez',62.0,to_date('7/12/14', 'MM/DD/RR'));
--Fila 97
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (97.0,'Salvador Dawson',33.0,to_date('10/22/10', 'MM/DD/RR'));
--Fila 98
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (98.0,'Tarik Hale',11.0,to_date('5/20/11', 'MM/DD/RR'));
--Fila 99
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (99.0,'Brent Holt',94.0,to_date('3/11/17', 'MM/DD/RR'));
--Fila 100
INSERT INTO EMPLOYEES (ID, FULL_NAME, MANAGER_ID, DATE_OF_JOINING) VALUES (100.0,'Ahmed Pruitt',92.0,to_date('3/6/11', 'MM/DD/RR'));


INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (500.0,'48205501099',9.0,3338179.0,to_date('04/01/2017', 'DD/MM/RR'),to_date('01/08/2017', 'DD/MM/RR'));
--Fila 2
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (501.0,'07503320299',3.0,4547667.0,to_date('06/03/2016', 'DD/MM/RR'),to_date('19/07/2018', 'DD/MM/RR'));
--Fila 3
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (502.0,'60671426199',3.0,2756133.0,to_date('22/05/2015', 'DD/MM/RR'),to_date('31/08/2018', 'DD/MM/RR'));
--Fila 4
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (503.0,'25416709099',10.0,4361180.0,to_date('11/09/2016', 'DD/MM/RR'),to_date('08/06/2018', 'DD/MM/RR'));
--Fila 5
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (504.0,'95623169399',3.0,4810339.0,to_date('08/08/2016', 'DD/MM/RR'),to_date('14/11/2017', 'DD/MM/RR'));
--Fila 6
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (505.0,'90287939499',4.0,3847133.0,to_date('20/01/2015', 'DD/MM/RR'),to_date('30/01/2018', 'DD/MM/RR'));
--Fila 7
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (506.0,'45539051699',8.0,2432283.0,to_date('16/10/2016', 'DD/MM/RR'),to_date('19/04/2018', 'DD/MM/RR'));
--Fila 8
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (507.0,'44905736599',5.0,1507239.0,to_date('30/05/2016', 'DD/MM/RR'),to_date('07/01/2019', 'DD/MM/RR'));
--Fila 9
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (508.0,'38742806799',4.0,2106491.0,to_date('17/06/2016', 'DD/MM/RR'),to_date('19/12/2017', 'DD/MM/RR'));
--Fila 10
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (509.0,'83225953299',2.0,2110767.0,to_date('08/12/2015', 'DD/MM/RR'),to_date('09/07/2018', 'DD/MM/RR'));
--Fila 11
INSERT INTO PROYECT (ID, CODE, MANAGER_ID, BUTGET, DATE_OF_BEGINNING, DATE_OF_ENDING) VALUES (510.0,'97296031099',10.0,2165874.0,to_date('11/07/2015', 'DD/MM/RR'),to_date('08/11/2017', 'DD/MM/RR'));




